#!/bin/bash
echo "Generating .env file from Codespaces secrets..."

cat <<EOF > .env
AIRFLOW_UID=1000
AIRFLOW_GID=0

AIRFLOW__SMTP__SMTP_HOST=sandbox.smtp.mailtrap.io
AIRFLOW__SMTP__SMTP_PORT=587
AIRFLOW__SMTP__SMTP_USER=${AIRFLOW__SMTP__SMTP_USER}
AIRFLOW__SMTP__SMTP_PASSWORD=${AIRFLOW__SMTP__SMTP_PASSWORD}
AIRFLOW__SMTP__SMTP_MAIL_FROM=${AIRFLOW__SMTP__SMTP_MAIL_FROM}
AIRFLOW__SMTP__SMTP_STARTTLS=True
AIRFLOW__SMTP__SMTP_SSL=False

ALERT_EMAILS=${ALERT_EMAILS}
EOF



